# Generated by Django 5.1.1 on 2025-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crop',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='produce_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', '유저'), ('FARMER', '농부')], default='유저', max_length=10),
        ),
    ]
