# Generated by Django 5.1.1 on 2025-02-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
